import { buildConfig } from '@optimizely/cms-sdk';

export default buildConfig({
  components: [
    './src/content-types/SeoBlock.ts',
    './src/content-types/SiteSettings.ts',
    './src/content-types/ArticlePage.ts',
    './src/content-types/PersonPage.ts',
    './src/content-types/PersonElement.ts',
    './src/content-types/CardBlock.ts',
    './src/content-types/TextElement.ts',
    './src/content-types/RichTextElement.ts',
    './src/content-types/ImageElement.ts',
    './src/content-types/BannerElement.ts',
    './src/content-types/CallToActionElement.ts',
    './src/content-types/PageCardElement.ts',
    './src/content-types/LandingPageExperience.ts',

    // Marketing blocks (Phase 4)
    './src/content-types/HeroBlock.ts',
    './src/content-types/StatsBlock.ts',
    './src/content-types/TestimonialBlock.ts',
    './src/content-types/ProcessBlock.ts',
    './src/content-types/CalloutBanner.ts',
    './src/content-types/SolutionTile.ts',
    './src/content-types/SolutionsGrid.ts',
    './src/content-types/PartnerLogos.ts',
    './src/content-types/AccordionItem.ts',
    './src/content-types/AccordionBlock.ts',
    './src/content-types/ArticleListBlock.ts',
    './src/content-types/ContactFormBlock.ts',
    './src/content-types/AdvancedHero.ts',

    './src/display-templates/CallToActionElementDisplayTemplate.ts',
    './src/display-templates/TextElementDisplayTemplate.ts',
    './src/display-templates/ImageElementDisplayTemplate.ts',
    './src/display-templates/LandingPageExperienceDisplayTemplate.ts',
    './src/display-templates/BlankSectionDisplayTemplate.ts',
    './src/display-templates/RowDisplayTemplate.ts',
    './src/display-templates/ColumnDisplayTemplate.ts',

    // Marketing block display templates (Phase 4)
    './src/display-templates/HeroBlockDisplayTemplate.ts',
    './src/display-templates/StatsBlockDisplayTemplate.ts',
    './src/display-templates/TestimonialBlockDisplayTemplate.ts',
    './src/display-templates/ProcessBlockDisplayTemplate.ts',
    './src/display-templates/CalloutBannerDisplayTemplate.ts',
    './src/display-templates/SolutionsGridDisplayTemplate.ts',
    './src/display-templates/PartnerLogosDisplayTemplate.ts',
    './src/display-templates/AccordionBlockDisplayTemplate.ts',
    './src/display-templates/ArticleListBlockDisplayTemplate.ts',
    './src/display-templates/ContactFormBlockDisplayTemplate.ts',
  ],
  propertyGroups: [
    { key: 'media', displayName: 'Media', sortOrder: 200 },
    { key: 'seo', displayName: 'SEO', sortOrder: 300 },
    { key: 'schema', displayName: 'Structured data', sortOrder: 350 },
    { key: 'socialMedia', displayName: 'Social Media', sortOrder: 400 },
    { key: 'organization', displayName: 'Organization', sortOrder: 500 },
  ],
});
